#!/bin/bash
set -ex

SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
DB_DIR="$SCRIPT_DIR/../db"

rm -rf "$DB_DIR/score-all-mainnet-beta"
rm -rf "$DB_DIR/score-all-testnet"
rm -rf "$DB_DIR/score-all-devnet"
