#!/bin/bash
set -ex

SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
BIN_DIR="$SCRIPT_DIR/../target/debug"
CSV_PATH="$SCRIPT_DIR/../db/score-all-mainnet-beta/mainnet-beta-validator-detail.csv"

# Clean files created by score-past-epoch program
"$SCRIPT_DIR/clean"

# Fetch sqlite db with past scores
"$SCRIPT_DIR/force-fetch-db"

# Score past epoch, the results are available in db/score-all-mainnet-beta directory
"$BIN_DIR/score-past-epoch" \
  --cluster mainnet-beta \
  --min-release-version 1.10.32 \
  --max-old-release-version-percentage 30 \
  $* \
  score-all \
  --score-max-commission 10 \
  --score-min-stake 100 \
  --concentration-point-discount 1500 \
  --min-avg-position 50

# Import CSV with the past scores into sqlite DB
"$SCRIPT_DIR/import-scores-into-db" "$CSV_PATH"
