#!/bin/bash

echo "Migration for gauge votes"

SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"

date
cd "$SCRIPT_DIR"

sqlite3 <<::END
.open ../db/score-sqlite3.db

create table migration as select
epoch, rank, score, marinade_score, 0 as collateral_score, 0 as collateral_shares, vote_score, votes_read, votes_effective ,   name ,  credits_observed ,  vote_address ,
commission ,  max_commission,  average_position ,  data_center_concentration ,  data_center_asn ,  data_center_location ,  avg_active_stake ,
apy ,  delinquent ,  this_epoch_credits ,  pct ,  marinade_staked ,  should_have  ,
remove_level ,  remove_level_reason,  under_nakamoto_coefficient ,  keybase_id ,  identity ,  stake_concentration ,  base_score ,  url ,  version
  from scores2
  ;

drop table scores2;
create table scores2 as select * from migration;
drop table migration;

.quit
::END
