#!/bin/bash
set -ex

SCRIPT_DIR=$(dirname "$0")
BIN_DIR="$SCRIPT_DIR/../target/debug"

date
"$BIN_DIR/score-past-epoch" --cluster mainnet-beta --markdown  $* \
   score-all \
   --score-max-commission 10 \
   --score-min-stake 100 \
   --concentration-point-discount 1500 \
   --min-avg-position 50
